version: '3'
services:
  blog:
    image: blog:v1
    container_name: blog-v1
    ports:
      - "4000:4000"
    volumes:
      - /home/linlin/LL_Play/Veraz00:/Veraz00
    command: /bin/bash
    tty: true
    stdin_open: true
    restart: "no"